apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oauth2-proxy-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    clientId: ${OAUTH2_PROXY_MANAGED_IDENTITY_CLIENT_ID}
    keyvaultName: ${AZURE_KEY_VAULT_NAME}
    cloudName: AzurePublicCloud
    tenantId: ${AZURE_TENANT_ID}
    objects: |
      array:
        - |
          objectName: oauth2-proxy-client-id
          objectType: secret
          objectAlias: oauth2-proxy-client-id
        - |
          objectName: oauth2-proxy-client-secret
          objectType: secret
          objectAlias: oauth2-proxy-client-secret
        - |
          objectName: oauth2-proxy-cookie-secret
          objectType: secret
          objectAlias: oauth2-proxy-cookie-secret
  secretObjects:
    - secretName: oauth2-proxy
      type: Opaque
      data:
        - objectName: oauth2-proxy-client-id
          key: OAUTH2_PROXY_CLIENT_ID
        - objectName: oauth2-proxy-client-secret
          key: OAUTH2_PROXY_CLIENT_SECRET
        - objectName: oauth2-proxy-cookie-secret
          key: OAUTH2_PROXY_COOKIE_SECRET
