apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mindwell

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - cronjob-data-sync.yaml
  - cronjob-summary-scheduler.yaml
  - cronjob-monitoring.yaml
