apiVersion: v1
kind: ServiceAccount
metadata:
  name: mindwell-agents
  labels:
    app: mindwell-agents
  annotations:
    azure.workload.identity/client-id: ${AKS_MANAGED_IDENTITY_CLIENT_ID}
    azure.workload.identity/use: "true"
